#!/bin/sh

config_file="$HOME/.local-model-config.env"
if [ -e "$config_file" ]; then
 set -o allexport
 . "$config_file"
 set +o allexport
fi
MODEL="${LLM_MODEL:-"unsloth/gemma-3-4b-it-GGUF:Q4_K_M"}"

if [ $# -eq 0 ]; then
 args=-i
else
 args="-st -p"
fi
exec llama-cli -hf "$MODEL" -c 0 $args "$@" 2>/dev/null
