#!/bin/sh

cat <<EOF>/tmp/models-preset.ini
version = 1

[gpt-oss:20b]
m=$(hf download bartowski/openai_gpt-oss-20b-GGUF openai_gpt-oss-20b-MXFP4.gguf)
jinja = on

[gemma-3-4b-it]
m=$(hf download unsloth/gemma-3-4b-it-GGUF gemma-3-4b-it-Q4_K_M.gguf)
mmproj=$(hf download unsloth/gemma-3-4b-it-GGUF mmproj-BF16.gguf)

[qwen3.5:9b]
m=$(hf download unsloth/Qwen3.5-9B-GGUF Qwen3.5-9B-Q4_K_M.gguf)
mmproj=$(hf download unsloth/Qwen3.5-9B-GGUF mmproj-BF16.gguf)
EOF

exec llama-server --host 0.0.0.0 --models-preset /tmp/models-preset.ini

