#!/usr/bin/env python3
import sys
from pathlib import Path
from prompt_toolkit.shortcuts import checkboxlist_dialog
from huggingface_hub import hf_hub_download
import subprocess

SELECTION_FILE = Path(__file__).resolve().parent / "selection.txt"

models = {
  "gpt-oss:20b": {"modelpath": "bartowski/openai_gpt-oss-20b-GGUF", "m": "openai_gpt-oss-20b-MXFP4.gguf", "jinja": "on"},
  "qwen3.5:9b": {"modelpath": "unsloth/Qwen3.5-9B-GGUF", "m": "Qwen3.5-9B-Q4_K_M.gguf", "mmproj": "mmproj-BF16.gguf"},
  "qwen3.5:27b": {"modelpath": "unsloth/Qwen3.5-9B-GGUF", "m": "Qwen3.5-27B-Q4_K_M.gguf", "mmproj": "mmproj-BF16.gguf"},
  "gemma-3-4b-it": {"modelpath": "unsloth/gemma-3-4b-it-GGUF", "m": "gemma-3-4b-it-Q4_K_M.gguf", "mmproj": "mmproj-BF16.gguf"},
  "gpt-oss:120b": {"modelpath": "bartowski/openai_gpt-oss-120b-GGUF", "m": "openai_gpt-oss-120b-MXFP4.gguf", "jinja": "on"}
}

def load_selection():
  if not SELECTION_FILE.exists():
    return set()
  return [line.strip() for line in SELECTION_FILE.read_text(encoding="utf-8").splitlines() if line.strip()]

def save_selection(selection):
  SELECTION_FILE.write_text("\n".join(selection) + ("\n" if selection else ""), encoding="utf-8")

def get_selection(prompt, items, previous_selection):
  default_values = [v | {"name": k} for k, v in items.items() if k in previous_selection]
 
  results = checkboxlist_dialog(text=prompt, values=[(v | {"name": n}, n) for n, v in items.items()], default_values=default_values).run()
  return {item["name"]: {k: v for k, v in item.items() if k != "name"} for item in results}

def get_models_presets(selection):
  result = "version = 1"

  for name, model in selection.items():
    model = model.copy()
    if 'modelpath' in model: 
      if 'm' in model: 
        model['m'] = hf_hub_download(repo_id=model['modelpath'], filename=model['m'])
      if 'mmproj' in model: 
        model['mmproj'] = hf_hub_download(repo_id=model['modelpath'], filename=model['mmproj'])
      del model['modelpath']
    result += f"\n\n[{name}]\n"+'\n'.join([n + '=' + v for n, v in model.items()])
  return result

if __name__ == "__main__":
  previous_selection = load_selection()
  
  if not previous_selection or len(sys.argv) > 1 and sys.argv[1] == '-select':
    selected = get_selection("Select models to use, then press Enter", models, previous_selection)
    save_selection(selected.keys())
  else:
    selected = {k: v for k, v in models.items() if k in previous_selection}

  with open("/tmp/models-preset.ini", "w") as f:
    f.write(get_models_presets(selected))
  subprocess.run(['llama-server', '--host', '0.0.0.0', '--models-preset', '/tmp/models-preset.ini'])
